import React, { useState, useEffect } from 'react';
import { 
  View, 
  Text, 
  StyleSheet, 
  ScrollView,
  TouchableOpacity,
  Alert,
  Share
} from 'react-native';
import { StatusBar } from 'expo-status-bar';
import Icon from 'react-native-vector-icons/MaterialIcons';
import { useAuth } from '../context/AuthContext';
import { getDocuments, deleteDocument as deleteDocumentFromFirestore } from '../api/firebase/firestore';
import Card from '../components/Card';
import ButtonPrimary from '../components/ButtonPrimary';
import colors from '../constants/colors';
import globalStyles from '../styles/globalStyles';

const DocumentsScreen = ({ navigation }) => {
  const { user } = useAuth();
  const [documents, setDocuments] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (user?.uid) {
      loadDocuments();
    } else {
      setLoading(false);
    }
  }, [user]);

  const loadDocuments = async () => {
    if (!user?.uid) {
      setLoading(false);
      return;
    }

    try {
      const docs = await getDocuments(user.uid);
      setDocuments(docs);
    } catch (error) {
      console.error('Error loading documents:', error);
    } finally {
      setLoading(false);
    }
  };

  const deleteDocument = async (id) => {
    Alert.alert(
      'Delete Document',
      'Are you sure you want to delete this document?',
      [
        { text: 'Cancel', style: 'cancel' },
        { 
          text: 'Delete', 
          style: 'destructive',
          onPress: async () => {
            try {
              await deleteDocumentFromFirestore(id);
              const updatedDocs = documents.filter(doc => doc.id !== id);
              setDocuments(updatedDocs);
            } catch (error) {
              console.error('Error deleting document:', error);
              Alert.alert('Error', 'Failed to delete document');
            }
          }
        }
      ]
    );
  };

  const shareDocument = async (document) => {
    try {
      await Share.share({
        message: `${document.title}\n\nGenerated by ProdigyPM Assistant\n\n${document.content}`,
        title: document.title,
      });
    } catch (error) {
      console.error('Error sharing document:', error);
    }
  };

  const getDocumentIcon = (type) => {
    switch (type) {
      case 'strategy': return 'lightbulb-outline';
      case 'prd': return 'description';
      case 'research': return 'search';
      case 'gtm': return 'rocket-launch';
      case 'backlog': return 'bar-chart';
      default: return 'description';
    }
  };

  const formatDate = (timestamp) => {
    return new Date(timestamp).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });
  };

  return (
    <View style={globalStyles.container}>
      <StatusBar style="light" backgroundColor={colors.pnc.primary} />
      
      {/* Header */}
      <View style={styles.header}>
        <TouchableOpacity onPress={() => navigation.goBack()}>
          <Text style={styles.backButton}>← Back</Text>
        </TouchableOpacity>
        <Text style={styles.headerTitle}>My Documents</Text>
        <View style={styles.placeholder} />
      </View>

      <ScrollView style={styles.content} showsVerticalScrollIndicator={false}>
        {loading ? (
          <View style={styles.loadingContainer}>
            <Text style={styles.loadingText}>Loading documents...</Text>
          </View>
        ) : documents.length === 0 ? (
          <View style={styles.emptyState}>
            <Icon name="description" size={64} color={colors.gray.medium} style={styles.emptyIcon} />
            <Text style={styles.emptyTitle}>No Documents Yet</Text>
            <Text style={styles.emptySubtitle}>
              Generate content with the AI Assistant to see your documents here.
            </Text>
            <ButtonPrimary
              title="Start Creating"
              onPress={() => navigation.goBack()}
              style={styles.createButton}
              noGradient
            />
          </View>
        ) : (
          <View style={styles.documentsContainer}>
            <Text style={styles.sectionTitle}>
              Generated Documents ({documents.length})
            </Text>
            
            {documents.map((document) => (
              <Card key={document.id} style={styles.documentCard}>
                <View style={styles.documentHeader}>
                  <View style={styles.documentMeta}>
                    <View style={styles.documentInfo}>
                      <Text style={styles.documentTitle}>{document.title}</Text>
                      <Text style={styles.documentDate}>
                        {formatDate(document.createdAt)}
                      </Text>
                    </View>
                  </View>
                  
                  <View style={styles.documentActions}>
                    <TouchableOpacity 
                      style={styles.actionButton}
                      onPress={() => shareDocument(document)}
                      accessibilityRole="button"
                      accessibilityLabel="Share document"
                    >
                      <Icon name="share" size={20} color={colors.pnc.secondary} />
                    </TouchableOpacity>
                    
                    <TouchableOpacity 
                      style={styles.actionButton}
                      onPress={() => deleteDocument(document.id)}
                      accessibilityRole="button"
                      accessibilityLabel="Delete document"
                    >
                      <Icon name="delete" size={20} color={colors.error} />
                    </TouchableOpacity>
                  </View>
                    <Icon 
                      name={getDocumentIcon(document.type)} 
                      size={24} 
                      color={colors.pnc.secondary} 
                      style={styles.documentIcon}
                    />
                </View>
                
                <View style={styles.documentPreview}>
                  <Text style={styles.previewText} numberOfLines={3}>
                    {document.content}
                  </Text>
                </View>
              </Card>
            ))}
          </View>
        )}
      </ScrollView>
    </View>
  );
};

const styles = StyleSheet.create({
  header: {
    backgroundColor: colors.pnc.primary,
    paddingHorizontal: 20,
    paddingVertical: 16,
    paddingTop: 60,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  backButton: {
    fontSize: 16,
    color: colors.white,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: colors.white,
  },
  placeholder: {
    width: 40, // Same width as back button for centering
  },
  content: {
    flex: 1,
    backgroundColor: colors.background.secondary,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: 100,
  },
  loadingText: {
    fontSize: 16,
    color: colors.text.secondary,
  },
  emptyState: {
    alignItems: 'center',
    paddingTop: 100,
    paddingHorizontal: 40,
  },
  emptyIcon: {
    marginBottom: 20,
  },
  emptyTitle: {
    fontSize: 24,
    fontWeight: '600',
    color: colors.text.primary,
    marginBottom: 12,
    textAlign: 'center',
  },
  emptySubtitle: {
    fontSize: 16,
    color: colors.text.secondary,
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: 32,
  },
  createButton: {
    paddingHorizontal: 32,
  },
  documentsContainer: {
    padding: 20,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: colors.text.primary,
    marginBottom: 16,
  },
  documentCard: {
    marginBottom: 16,
    padding: 16,
  },
  documentHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 12,
  },
  documentMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  documentIcon: {
    marginRight: 12,
  },
  documentInfo: {
    flex: 1,
  },
  documentTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.text.primary,
    marginBottom: 4,
  },
  documentDate: {
    fontSize: 12,
    color: colors.text.secondary,
  },
  documentActions: {
    flexDirection: 'row',
  },
  actionButton: {
    padding: 8,
    marginLeft: 8,
  },
  documentPreview: {
    backgroundColor: colors.background.secondary,
    borderRadius: 8,
    padding: 12,
  },
  previewText: {
    fontSize: 14,
    color: colors.text.secondary,
    lineHeight: 20,
  },
});

export default DocumentsScreen;