import React, { useState, useEffect } from 'react';
import { 
  View, 
  Text, 
  StyleSheet, 
  ScrollView,
  TouchableOpacity,
  Alert,
  Share,
  Linking
} from 'react-native';
import { StatusBar } from 'expo-status-bar';
import Icon from 'react-native-vector-icons/MaterialIcons';
import * as Sharing from 'expo-sharing';
import { useAuth } from '../context/AuthContext';
import { getDocuments, deleteDocument as deleteDocumentFromFirestore } from '../api/firebase/firestore';
import Card from '../components/Card';
import ButtonPrimary from '../components/ButtonPrimary';
import colors from '../constants/colors';
import globalStyles from '../styles/globalStyles';

const DocumentsScreen = ({ navigation }) => {
  const { user } = useAuth();
  const [documents, setDocuments] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (user?.uid) {
      loadDocuments();
    } else {
      setLoading(false);
    }
  }, [user]);

  const loadDocuments = async () => {
    if (!user?.uid) {
      setLoading(false);
      return;
    }

    try {
      const docs = await getDocuments(user.uid);
      setDocuments(docs);
    } catch (error) {
      console.error('Error loading documents:', error);
    } finally {
      setLoading(false);
    }
  };

  const deleteDocument = async (id) => {
    Alert.alert(
      'Delete Document',
      'Are you sure you want to delete this document?',
      [
        { text: 'Cancel', style: 'cancel' },
        { 
          text: 'Delete', 
          style: 'destructive',
          onPress: async () => {
            try {
              await deleteDocumentFromFirestore(id);
              const updatedDocs = documents.filter(doc => doc.id !== id);
              setDocuments(updatedDocs);
            } catch (error) {
              console.error('Error deleting document:', error);
              Alert.alert('Error', 'Failed to delete document');
            }
          }
        }
      ]
    );
  };

  const shareDocument = async (document) => {
    try {
      // If PDF exists, share the PDF file
      if (document.pdfUri && await Sharing.isAvailableAsync()) {
        await Sharing.shareAsync(document.pdfUri);
      } else {
        // Fallback to text sharing
        await Share.share({
          message: `${document.title}\n\nGenerated by ProdigyPM Assistant\n\n${document.content}`,
          title: document.title,
        });
      }
    } catch (error) {
      console.error('Error sharing document:', error);
      Alert.alert('Error', 'Failed to share document');
    }
  };

  const openPDF = async (document) => {
    if (!document.pdfUri) {
      Alert.alert('No PDF', 'This document does not have an associated PDF file.');
      return;
    }

    try {
      if (await Sharing.isAvailableAsync()) {
        await Sharing.shareAsync(document.pdfUri);
      } else {
        Alert.alert('Not Available', 'PDF sharing is not available on this device.');
      }
    } catch (error) {
      console.error('Error opening PDF:', error);
      Alert.alert('Error', 'Failed to open PDF');
    }
  };

  const getDocumentIcon = (type) => {
    switch (type) {
      case 'strategy': return 'lightbulb-outline';
      case 'prd': return 'description';
      case 'research': return 'search';
      case 'gtm': return 'rocket-launch';
      case 'backlog': return 'bar-chart';
      default: return 'description';
    }
  };

  const formatDate = (timestamp) => {
    return new Date(timestamp).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });
  };

  return (
    <View style={globalStyles.container}>
      <StatusBar style="light" backgroundColor={colors.pnc.primary} />
      
      {/* Header */}
      <View style={styles.header}>
        <TouchableOpacity onPress={() => navigation.goBack()}>
          <Text style={styles.backButton}>← Back</Text>
        </TouchableOpacity>
        <Text style={styles.headerTitle}>My Documents</Text>
        <View style={styles.placeholder} />
      </View>

      <ScrollView style={styles.content} showsVerticalScrollIndicator={false}>
        {loading ? (
          <View style={styles.loadingContainer}>
            <Text style={styles.loadingText}>Loading documents...</Text>
          </View>
        ) : documents.length === 0 ? (
          <View style={styles.emptyState}>
            <Icon name="description" size={64} color={colors.gray.medium} style={styles.emptyIcon} />
            <Text style={styles.emptyTitle}>No Documents Yet</Text>
            <Text style={styles.emptySubtitle}>
              Generate content with the AI Assistant to see your documents here.
            </Text>
            <ButtonPrimary
              title="Start Creating"
              onPress={() => navigation.goBack()}
              style={styles.createButton}
              noGradient
            />
          </View>
        ) : (
          <View style={styles.documentsContainer}>
            <Text style={styles.sectionTitle}>
              Generated Documents ({documents.length})
            </Text>
            
            {documents.map((document) => (
              <Card key={document.id} style={styles.documentCard}>
                {/* Header with icon and title */}
                <View style={styles.documentHeader}>
                  <View style={styles.iconContainer}>
                    <Icon 
                      name={getDocumentIcon(document.type)} 
                      size={28} 
                      color={colors.pnc.secondary} 
                    />
                  </View>
                  
                  <View style={styles.documentInfo}>
                    <View style={styles.titleRow}>
                      <Text style={styles.documentTitle} numberOfLines={2}>
                        {document.title}
                      </Text>
                    </View>
                    <View style={styles.metaRow}>
                      <Icon name="schedule" size={14} color={colors.text.secondary} />
                      <Text style={styles.documentDate}>
                        {formatDate(document.createdAt)}
                      </Text>
                      {document.pdfUri && (
                        <View style={styles.pdfBadge}>
                          <Icon name="picture-as-pdf" size={10} color={colors.white} />
                          <Text style={styles.pdfBadgeText}>PDF</Text>
                        </View>
                      )}
                    </View>
                  </View>
                </View>
                
                {/* Content Preview */}
                <View style={styles.documentPreview}>
                  <Text style={styles.previewText} numberOfLines={3}>
                    {document.content}
                  </Text>
                </View>
                
                {/* Action Buttons */}
                <View style={styles.actionBar}>
                  {document.pdfUri && (
                    <TouchableOpacity 
                      style={styles.actionButtonWithLabel}
                      onPress={() => openPDF(document)}
                      accessibilityRole="button"
                      accessibilityLabel="Open PDF"
                    >
                      <Icon name="picture-as-pdf" size={18} color={colors.pnc.secondary} />
                      <Text style={styles.actionButtonText}>Open PDF</Text>
                    </TouchableOpacity>
                  )}
                  <TouchableOpacity 
                    style={styles.actionButtonWithLabel}
                    onPress={() => shareDocument(document)}
                    accessibilityRole="button"
                    accessibilityLabel="Share document"
                  >
                    <Icon name="share" size={18} color={colors.pnc.secondary} />
                    <Text style={styles.actionButtonText}>Share</Text>
                  </TouchableOpacity>
                  
                  <TouchableOpacity 
                    style={styles.actionButtonWithLabel}
                    onPress={() => deleteDocument(document.id)}
                    accessibilityRole="button"
                    accessibilityLabel="Delete document"
                  >
                    <Icon name="delete" size={18} color={colors.error} />
                    <Text style={[styles.actionButtonText, { color: colors.error }]}>Delete</Text>
                  </TouchableOpacity>
                </View>
              </Card>
            ))}
          </View>
        )}
      </ScrollView>
    </View>
  );
};

const styles = StyleSheet.create({
  header: {
    backgroundColor: colors.pnc.primary,
    paddingHorizontal: 20,
    paddingVertical: 16,
    paddingTop: 60,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  backButton: {
    fontSize: 16,
    color: colors.white,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: colors.white,
  },
  placeholder: {
    width: 40, // Same width as back button for centering
  },
  content: {
    flex: 1,
    backgroundColor: colors.background.secondary,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: 100,
  },
  loadingText: {
    fontSize: 16,
    color: colors.text.secondary,
  },
  emptyState: {
    alignItems: 'center',
    paddingTop: 100,
    paddingHorizontal: 40,
  },
  emptyIcon: {
    marginBottom: 20,
  },
  emptyTitle: {
    fontSize: 24,
    fontWeight: '600',
    color: colors.text.primary,
    marginBottom: 12,
    textAlign: 'center',
  },
  emptySubtitle: {
    fontSize: 16,
    color: colors.text.secondary,
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: 32,
  },
  createButton: {
    paddingHorizontal: 32,
  },
  documentsContainer: {
    padding: 20,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: colors.text.primary,
    marginBottom: 16,
  },
  documentCard: {
    marginBottom: 16,
    padding: 0,
    overflow: 'hidden',
  },
  documentHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    paddingBottom: 12,
    backgroundColor: colors.background.primary,
  },
  iconContainer: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: colors.background.orange,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  documentInfo: {
    flex: 1,
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 6,
  },
  documentTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.text.primary,
    flex: 1,
    lineHeight: 22,
  },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  documentDate: {
    fontSize: 12,
    color: colors.text.secondary,
    marginLeft: 4,
  },
  pdfBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.pnc.secondary,
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderRadius: 10,
    marginLeft: 8,
    gap: 3,
  },
  pdfBadgeText: {
    fontSize: 9,
    fontWeight: '700',
    color: colors.white,
    letterSpacing: 0.5,
  },
  documentPreview: {
    backgroundColor: colors.background.secondary,
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: colors.borderLight,
  },
  previewText: {
    fontSize: 13,
    color: colors.text.secondary,
    lineHeight: 20,
  },
  actionBar: {
    flexDirection: 'row',
    borderTopWidth: 1,
    borderTopColor: colors.borderLight,
    paddingVertical: 8,
    paddingHorizontal: 8,
    justifyContent: 'space-around',
    backgroundColor: colors.white,
  },
  actionButtonWithLabel: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    gap: 6,
  },
  actionButtonText: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.pnc.secondary,
  },
});

export default DocumentsScreen;