import colors from '../constants/colors';

// React Native Paper theme configuration
export default {
  colors: {
    primary: colors.pnc.primary,
    primaryContainer: colors.pnc.lightBlue,
    secondary: colors.pnc.secondary,
    secondaryContainer: colors.pnc.lightBlue,
    tertiary: colors.pnc.orange,
    tertiaryContainer: '#FFF8E1',
    surface: colors.white,
    surfaceVariant: colors.gray.light,
    surfaceDisabled: colors.gray.medium,
    background: colors.background.primary,
    error: colors.error,
    errorContainer: '#FFEBEE',
    onPrimary: colors.white,
    onPrimaryContainer: colors.pnc.darkBlue,
    onSecondary: colors.white,
    onSecondaryContainer: colors.pnc.darkBlue,
    onTertiary: colors.black,
    onTertiaryContainer: colors.black,
    onSurface: colors.text.primary,
    onSurfaceVariant: colors.text.secondary,
    onSurfaceDisabled: colors.gray.medium,
    onError: colors.white,
    onErrorContainer: colors.error,
    onBackground: colors.text.primary,
    outline: colors.gray.medium,
    outlineVariant: colors.gray.light,
    inverseSurface: colors.gray.darker,
    inverseOnSurface: colors.white,
    inversePrimary: colors.pnc.lightBlue,
    shadow: colors.black,
    scrim: colors.black,
    backdrop: 'rgba(0, 0, 0, 0.5)',
  },
  roundness: 8,
};