// Go-to-Market checklist template for PNC Bank product launches
export default {
  categories: [
    {
      id: 'pre-launch',
      name: 'Pre-Launch Preparation',
      color: '#0069AA',
      items: [
        {
          id: 'legal-review',
          task: 'Complete legal and compliance review',
          description: 'Ensure all regulatory requirements are met for financial services',
          owner: 'Legal & Compliance',
          timeline: '6-8 weeks before launch',
          priority: 'high',
          estimatedHours: 40,
          completed: false,
        },
        {
          id: 'security-audit',
          task: 'Conduct comprehensive security audit',
          description: 'Penetration testing and security vulnerability assessment',
          owner: 'Security Team',
          timeline: '4-6 weeks before launch',
          priority: 'high',
          estimatedHours: 60,
          completed: false,
        },
        {
          id: 'regulatory-approval',
          task: 'Obtain regulatory approvals',
          description: 'Submit required documentation to financial regulators',
          owner: 'Regulatory Affairs',
          timeline: '8-12 weeks before launch',
          priority: 'high',
          estimatedHours: 80,
          completed: false,
        },
        {
          id: 'risk-assessment',
          task: 'Complete operational risk assessment',
          description: 'Identify and mitigate operational risks',
          owner: 'Risk Management',
          timeline: '4 weeks before launch',
          priority: 'high',
          estimatedHours: 24,
          completed: false,
        },
      ],
    },
    {
      id: 'product-readiness',
      name: 'Product Readiness',
      color: '#0069AA',
      items: [
        {
          id: 'uat-testing',
          task: 'User Acceptance Testing completion',
          description: 'Complete UAT with real users and scenarios',
          owner: 'QA Team',
          timeline: '3 weeks before launch',
          priority: 'high',
          estimatedHours: 120,
          completed: false,
        },
        {
          id: 'load-testing',
          task: 'Performance and load testing',
          description: 'Test system under expected production load',
          owner: 'Engineering',
          timeline: '3 weeks before launch',
          priority: 'high',
          estimatedHours: 40,
          completed: false,
        },
        {
          id: 'documentation',
          task: 'Complete product documentation',
          description: 'User guides, API docs, troubleshooting guides',
          owner: 'Product Team',
          timeline: '2 weeks before launch',
          priority: 'medium',
          estimatedHours: 32,
          completed: false,
        },
        {
          id: 'rollback-plan',
          task: 'Prepare rollback procedures',
          description: 'Document rollback steps in case of issues',
          owner: 'Engineering',
          timeline: '1 week before launch',
          priority: 'high',
          estimatedHours: 16,
          completed: false,
        },
      ],
    },
    {
      id: 'marketing-communications',
      name: 'Marketing & Communications',
      color: '#F58025',
      items: [
        {
          id: 'marketing-campaign',
          task: 'Launch marketing campaign',
          description: 'Email, social media, website updates',
          owner: 'Marketing Team',
          timeline: '2 weeks before launch',
          priority: 'medium',
          estimatedHours: 60,
          completed: false,
        },
        {
          id: 'press-release',
          task: 'Prepare and distribute press release',
          description: 'Announce product launch to media',
          owner: 'PR Team',
          timeline: '1 week before launch',
          priority: 'medium',
          estimatedHours: 20,
          completed: false,
        },
        {
          id: 'internal-announcement',
          task: 'Internal team announcement',
          description: 'Inform all PNC employees about the launch',
          owner: 'Internal Communications',
          timeline: '3 days before launch',
          priority: 'medium',
          estimatedHours: 8,
          completed: false,
        },
        {
          id: 'website-updates',
          task: 'Update website and mobile app',
          description: 'Reflect new product in digital channels',
          owner: 'Digital Team',
          timeline: 'Launch day',
          priority: 'high',
          estimatedHours: 16,
          completed: false,
        },
      ],
    },
    {
      id: 'sales-enablement',
      name: 'Sales Enablement',
      color: '#4CAF50',
      items: [
        {
          id: 'sales-training',
          task: 'Sales team training sessions',
          description: 'Train sales staff on new product features',
          owner: 'Sales Training',
          timeline: '2 weeks before launch',
          priority: 'high',
          estimatedHours: 40,
          completed: false,
        },
        {
          id: 'sales-materials',
          task: 'Create sales collateral',
          description: 'Brochures, presentation decks, FAQs',
          owner: 'Sales Operations',
          timeline: '2 weeks before launch',
          priority: 'medium',
          estimatedHours: 32,
          completed: false,
        },
        {
          id: 'pricing-guide',
          task: 'Finalize pricing and fee structure',
          description: 'Complete pricing documentation for sales team',
          owner: 'Product Team',
          timeline: '3 weeks before launch',
          priority: 'high',
          estimatedHours: 24,
          completed: false,
        },
      ],
    },
    {
      id: 'customer-support',
      name: 'Customer Support',
      color: '#9C27B0',
      items: [
        {
          id: 'support-training',
          task: 'Customer support training',
          description: 'Train support team on new product',
          owner: 'Customer Support',
          timeline: '2 weeks before launch',
          priority: 'high',
          estimatedHours: 32,
          completed: false,
        },
        {
          id: 'knowledge-base',
          task: 'Update knowledge base articles',
          description: 'Create support articles for common questions',
          owner: 'Customer Support',
          timeline: '1 week before launch',
          priority: 'medium',
          estimatedHours: 20,
          completed: false,
        },
        {
          id: 'escalation-procedures',
          task: 'Define escalation procedures',
          description: 'Clear escalation path for complex issues',
          owner: 'Support Manager',
          timeline: '1 week before launch',
          priority: 'medium',
          estimatedHours: 8,
          completed: false,
        },
      ],
    },
    {
      id: 'launch-day',
      name: 'Launch Day Activities',
      color: '#F44336',
      items: [
        {
          id: 'system-monitoring',
          task: 'Monitor system performance',
          description: 'Real-time monitoring of all systems',
          owner: 'DevOps Team',
          timeline: 'Launch day',
          priority: 'high',
          estimatedHours: 8,
          completed: false,
        },
        {
          id: 'communication-ready',
          task: 'Communication channels ready',
          description: 'War room for immediate issue resolution',
          owner: 'Product Manager',
          timeline: 'Launch day',
          priority: 'high',
          estimatedHours: 8,
          completed: false,
        },
        {
          id: 'feature-flags',
          task: 'Activate feature flags',
          description: 'Enable new product features in production',
          owner: 'Engineering',
          timeline: 'Launch day',
          priority: 'high',
          estimatedHours: 2,
          completed: false,
        },
      ],
    },
    {
      id: 'post-launch',
      name: 'Post-Launch Monitoring',
      color: '#607D8B',
      items: [
        {
          id: 'metrics-tracking',
          task: 'Monitor launch metrics',
          description: 'Track adoption, usage, and performance KPIs',
          owner: 'Analytics Team',
          timeline: '1-7 days after launch',
          priority: 'high',
          estimatedHours: 20,
          completed: false,
        },
        {
          id: 'feedback-collection',
          task: 'Collect customer feedback',
          description: 'Gather initial user feedback and issues',
          owner: 'Customer Success',
          timeline: '1-14 days after launch',
          priority: 'medium',
          estimatedHours: 16,
          completed: false,
        },
        {
          id: 'retrospective',
          task: 'Launch retrospective meeting',
          description: 'Review what went well and areas for improvement',
          owner: 'Product Manager',
          timeline: '1 week after launch',
          priority: 'medium',
          estimatedHours: 4,
          completed: false,
        },
        {
          id: 'optimization-plan',
          task: 'Create optimization roadmap',
          description: 'Plan improvements based on launch learnings',
          owner: 'Product Team',
          timeline: '2 weeks after launch',
          priority: 'medium',
          estimatedHours: 16,
          completed: false,
        },
      ],
    },
  ],
  
  // Summary statistics
  getTotalTasks: function() {
    return this.categories.reduce((total, category) => total + category.items.length, 0);
  },
  
  getCompletedTasks: function() {
    return this.categories.reduce((total, category) => 
      total + category.items.filter(item => item.completed).length, 0
    );
  },
  
  getHighPriorityTasks: function() {
    return this.categories.reduce((total, category) => 
      total + category.items.filter(item => item.priority === 'high').length, 0
    );
  },
  
  getTotalEstimatedHours: function() {
    return this.categories.reduce((total, category) => 
      total + category.items.reduce((catTotal, item) => catTotal + item.estimatedHours, 0), 0
    );
  },
};